version: "2"
services:
  backend:
    depends_on:
      - db
    image: oussamalachiheb/khaddem:1.0
    ports:
      - "8089:8089"

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: khaddemApp
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"

  angular:
    image: oussamalachiheb/khaddem-frontend:latest
    ports:
      - "80:80"
    container_name: khaddem-frontend
